      program main

c*********************************************************************72
c
cc MAIN is the main program for GRAFIK_PRB.
c
C  THEN USE TEKPLT TO EXAMINE THE PLOTFILES NAMED GRAF01.DAT,
C  GRAF02.DAT, GRAF03.DAT, GRAF04.DAT AND GRAF05.DAT CREATED ON YOUR
C  ACCOUNT BY THE PROGRAM.  COPIES OF THE PLOTFILES MADE BY THIS PROGRAM
C  ARE ALREADY AVAILABLE ON THE MTH: LIBRARY.
C
C  FOR DETAILS ON USING GRAFIK, SEE THE HELP FILE MTH:GRAFIK.HLP.
C
      LOGICAL      CALCOM
      DIMENSION    JOIN(20)
      CHARACTER*30 PLOTNM
      LOGICAL      PLOT10
      CHARACTER*80 TITLE
      DIMENSION    VAL(16,16)
      DIMENSION    VLEVEL(20)
      DIMENSION    V1(12)
      DIMENSION    V2(12)
      DIMENSION    X(16)
      DIMENSION    XB(20)
      DIMENSION    Y(16)
      DIMENSION    YB(20)
C
C  SET PLOT OPTIONS
C
      CALCOM=.TRUE.
      PLOT10=.TRUE.
C
C  FIRST PREPARE TO SET UP A VECTOR PLOT
C
      PLOTNM='GRAF01.DAT'
C
C  STORE THE TITLE
C
      NCHAR=23
      TITLE='GRAF01.DAT  VECTOR PLOT'
      NVAL=12
C
C  SET UP X,Y COORDINATES FOR EVERY POINT
C
      X(1)=.2
      Y(1)=.4
      X(2)=.2
      Y(2)=.6
      X(3)=.2
      Y(3)=.8
      X(4)=.4
      Y(4)=.6
      X(5)=.4
      Y(5)=.8
      X(6)=.6
      Y(6)=.4
      X(7)=.6
      Y(7)=.6
      X(8)=.6
      Y(8)=.8
      X(9)=.8
      Y(9)=.2
      X(10)=0.8
      Y(10)=0.4
      X(11)=.8
      Y(11)=.6
      X(12)=.8
      Y(12)=.8
C
C  SET UP VECTOR QUANTITY V1,V2 FOR EACH POINT
C
      DO I=1,NVAL
        V1(I)=X(I)
        V2(I)=Y(I)
      end do
C
C  SET UP ENDPOINTS OF LINES TO BE DRAWN IN PLOT
C
      NB=10
      XB(1)=0.0
      YB(1)=0.0
      JOIN(1)=1
      XB(2)=.2
      YB(2)=.2
      JOIN(2)=1
      XB(3)=.4
      YB(3)=.2
      JOIN(3)=1
      XB(4)=.4
      YB(4)=.4
      JOIN(4)=1
      XB(5)=1.0
      YB(5)=0.0
      JOIN(5)=1
      XB(6)=1.0
      YB(6)=1.0
      JOIN(6)=1
      XB(7)=0.0
      YB(7)=1.0
      JOIN(7)=1
      XB(8)=0.0
      YB(8)=0.0
      JOIN(8)=0
      XB(9)=0.5
      YB(9)=.5
      JOIN(9)=1
      XB(10)=1.0
      YB(10)=.5
      JOIN(10)=0
C
C  SET VECTOR SCALE FACTOR
C
      VSCALE=0.20
C
C  SET PLOTSIZE
C
      XSIZE=4.0
      YSIZE=6.0
      XMARGL=1.5
      XMARGR=1.5
      YMARGT=1.0
      YMARGB=0.5
      CALL SETSIZ(XMARGL,XMARGR,XSIZE,YMARGB,YMARGT,YSIZE)
      CALL VCPLOT(X,Y,V1,V2,NVAL,XB,YB,JOIN,NB,PLOTNM,TITLE,NCHAR,
     1 VSCALE,CALCOM,PLOT10)
C
C  PERFORM CONTOUR PLOTS ON NEW REGION
C
      NROW=16
      NCOL=16
C
C  SET X AND Y FOR ROWS AND COLUMNS
C
      DO I=1,NCOL
        X(I)=(REAL(NCOL-I)*(-2.0)+REAL(I-1)*2.0)/REAL(NCOL-1)
      end do

      DO I=1,NROW
        Y(I)=(REAL(NROW-I)*(-3.0)+REAL(I-1)*3.0)/REAL(NROW-1)
      end do
C
C  SET FUNCTION VALUE FOR EVERY POINT
C
      DO I=1,NROW
        DO J=1,NCOL
          VAL(I,J)=X(J)*X(J)-0.33*Y(I)*Y(I)+X(J)-Y(I)+1.0
        end do
      end do
C
C  SET A FLAG VALUE, AND RESET CERTAIN FUNCTION VALUES
C  NORMALLY, IF NO FUNCTION VALUE WAS AVAILABLE FOR A POINT,
C  THE FLAG VALUE WOULD BE USED
C
      FLAG=-200.0
      VAL(1,1)=FLAG
      VAL(1,2)=FLAG
      VAL(1,3)=FLAG
      VAL(1,4)=FLAG
      VAL(2,4)=FLAG
      VAL(3,4)=FLAG
      VAL(8,8)=FLAG
C
C  SET ENDPOINTS OF AUXILLIARY LINES
C
      XB(1)=X(7)
      YB(1)=Y(7)
      JOIN(1)=1
      XB(2)=X(7)
      YB(2)=Y(9)
      JOIN(2)=1
      XB(3)=X(9)
      YB(3)=Y(9)
      JOIN(3)=1
      XB(4)=X(9)
      YB(4)=Y(7)
      JOIN(4)=1
      XB(5)=X(7)
      YB(5)=Y(7)
      JOIN(5)=0
      NB=5
C
C  PERFORM CONTOUR PLOT WITH EVENLY SPACED DATA BETWEEN
C  MINIMUM AND MAXIMUM FUNCTION VALUES
C  (CENTERED LEVELS, EXCLUDING ENDPOINTS)
C
      NLEVEL=10
      IOPT=0
      PLOTNM='GRAF02.DAT'
C
C  STORE THE TITLE
C
      NCHAR=40
      TITLE='GRAF02.DAT  CONTOUR PLOT  DEFAULT LIMITS'
C
C  SET THE MAXIMUM ROW DIMENSION OF VAL
C
      MAXROW=16
C
C  CALL COPLOT
C
      CALL COPLOT(NROW,NCOL,X,Y,VAL,FLAG,NLEVEL,VLEVEL,IOPT,XB,
     1 YB,JOIN,NB,PLOTNM,TITLE,NCHAR,MAXROW,CALCOM,PLOT10)
C
C  PERFORM CONTOUR PLOT OF SAME DATA BUT USING EVENLY SPACED
C  STAGGERED LEVELS BETWEEN -1.0 AND +1.0
C
C  ALSO, HAVE COPLOT DO FILLIN OF DATA
C
      VLEVEL(1)=0.0
      VLEVEL(2)=+2.0
      IOPT=3
      NLEVEL=7
C
C  SET FLAG VALUE POSITIVE
C  AND RESET MISSING DATA TO NEW FLAG VALUE
C
      FLAG=200.0
      VAL(1,1)=FLAG
      VAL(1,2)=FLAG
      VAL(1,3)=FLAG
      VAL(1,4)=FLAG
      VAL(2,4)=FLAG
      VAL(3,4)=FLAG
      VAL(8,8)=FLAG
C
C   SET PLOTFILE NAME
C
      PLOTNM='GRAF03.DAT'
C
C  STORE THE TITLE
C
      NCHAR=37
      TITLE='GRAF03.DAT  CONTOUR PLOT  USER LIMITS'
C
C  SET MAXIMUM ROW DIMENSION OF VAL
C
      MAXROW=16
C
C  CALL COPLOT
C
      CALL COPLOT(NROW,NCOL,X,Y,VAL,FLAG,NLEVEL,VLEVEL,IOPT,XB,
     1 YB,JOIN,NB,PLOTNM,TITLE,NCHAR,MAXROW,CALCOM,PLOT10)
C
C  PERFORM CONTOUR PLOT OF SIN(X)*SIN(3Y), SPECIFYING LEVELS
C
C  SET SIZE OF PLOT
C
      XSIZE=3.0
      YSIZE=6.0
      XMARGL=0.0
      XMARGR=0.0
      YMARGT=1.0
      YMARGB=0.0
      CALL SETSIZ(XMARGL,XMARGR,XSIZE,YMARGB,YMARGT,YSIZE)
C
C  SET CONTOUR LEVELS
C
      VLEVEL(1)=-0.95
      VLEVEL(2)=-0.75
      VLEVEL(3)=-0.55
      VLEVEL(4)=-0.35
      VLEVEL(5)=-0.15
      VLEVEL(6)=0.0
      VLEVEL(7)=0.15
      VLEVEL(8)=0.35
      VLEVEL(9)=0.55
      VLEVEL(10)=0.75
      VLEVEL(11)=0.95
      IOPT=4
      NLEVEL=11
C
C  SET X, Y
C
      PI=3.14159265
      NCOL=16
      NROW=16
      DO I=1,NCOL
        X(I)=REAL(I-1)*PI/REAL(NCOL-1)
      end do
      DO I=1,NROW
        Y(I)=REAL(I-1)*PI/REAL(NROW-1)
      end do
      DO I=1,NROW
        DO J=1,NCOL
          VAL(I,J)=SIN(X(J))*SIN(3.0*Y(I))
        end do
      end do
C
C  SET FLAG VALUE
C
      FLAG=-20.0
C
C  SET PLOT NAME
C
      PLOTNM='GRAF04.DAT'
C
C  SET NO BOUNDARIES
C
      NB=0
C
C  STORE THE TITLE
C
      NCHAR=37
      TITLE='GRAF04.DAT  CONTOUR PLOT  USER LEVELS'
C
C  SET MAXIMUM ROW DIMENSION OF VAL
C
      MAXROW=16
C
C  CALL COPLOT
C
      CALL COPLOT(NROW,NCOL,X,Y,VAL,FLAG,NLEVEL,VLEVEL,IOPT,XB,
     1 YB,JOIN,NB,PLOTNM,TITLE,NCHAR,MAXROW,CALCOM,PLOT10)
C
C  PERFORM CONTOUR PLOTS ON NEW REGION
C  WITH 'DEGENERATE' CONTOUR LINE WHICH IS IN FACT A PLANE REGION
C  PROGRAM WILL DRAW 'LINE' BY FILLING REGION IN WITH
C  LITTLE TRIANGLES
C
C  RESTORE DEFAULT PLOT SIZES
C
      CALL DEFSIZ
C
C  SET NUMBER OF ROWS AND COLUMNS
C
      NROW=11
      NCOL=11
C
C  SET X AND Y FOR ROWS AND COLUMNS
C
      DO I=1,NCOL
        X(I)=(REAL(NCOL-I)*(-1.0)+REAL(I-1)*1.0)/REAL(NCOL-1)
      end do

      DO I=1,NROW
        Y(I)=(REAL(NROW-I)*(-1.0)+REAL(I-1)*1.0)/REAL(NROW-1)
      end do
C
C  SET FUNCTION VALUE FOR EVERY POINT
C
      DO I=1,NROW
        DO J=1,NCOL
          VAL(I,J)=0.0
          IF(ABS(X(J)).GE.ABS(Y(I)))VAL(I,J)=1.0
        end do
      end do
C
C  SET ENDPOINTS OF AUXILLIARY LINES
C
      NB=0
      NLEVEL=1
      IOPT=4
      VLEVEL(1)=1.0
      PLOTNM='GRAF05.DAT'
C
C  STORE THE TITLE
C
      NCHAR=35
      TITLE='GRAF05.DAT  DEGENERATE CONTOUR PLOT'
      FLAG=99.0
C
C  SET MAXIMUM ROW DIMENSION OF VAL
C
      MAXROW=16
C
C  CALL COPLOT
C
      CALL COPLOT(NROW,NCOL,X,Y,VAL,FLAG,NLEVEL,VLEVEL,IOPT,XB,
     1 YB,JOIN,NB,PLOTNM,TITLE,NCHAR,MAXROW,CALCOM,PLOT10)

      STOP
      END
